#############################################################################
# Makefile for building: LINEFOLLOWER
# Generated by qmake (2.01a) (Qt 4.8.7) on: czw. cze 8 12:36:00 2017
# Project:  pro/LINEFOLLOWER.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile.app pro/LINEFOLLOWER.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -Ipro -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Iinc -Iui/inc -I.inc -I.inc/qcustomplot -I./res/inc -I./ui/inc -Ipro -Iinc -Iinc/qcustomplot -Iinc/rs232 -Iout/moc -Iout/uic -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/czujniki.cpp \
		src/data.cpp \
		src/info.cpp \
		src/main.cpp \
		src/mainwindow.cpp \
		src/trasa.cpp \
		src/wykres.cpp \
		src/qcustomplot/qcustomplot.cpp \
		src/rs232/odbieranie.cpp \
		src/rs232/transparam.cpp out/moc/moc_qcustomplot.cpp \
		out/moc/moc_czujniki.cpp \
		out/moc/moc_info.cpp \
		out/moc/moc_trasa.cpp \
		out/moc/moc_wykres.cpp \
		out/moc/moc_mainwindow.cpp \
		out/rcc/qrc_pcb.cpp
OBJECTS       = obj/czujniki.o \
		obj/data.o \
		obj/info.o \
		obj/main.o \
		obj/mainwindow.o \
		obj/trasa.o \
		obj/wykres.o \
		obj/qcustomplot.o \
		obj/odbieranie.o \
		obj/transparam.o \
		obj/moc_qcustomplot.o \
		obj/moc_czujniki.o \
		obj/moc_info.o \
		obj/moc_trasa.o \
		obj/moc_wykres.o \
		obj/moc_mainwindow.o \
		obj/qrc_pcb.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		pro/LINEFOLLOWER.pro
QMAKE_TARGET  = LINEFOLLOWER
DESTDIR       = 
TARGET        = LINEFOLLOWER

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile.app $(TARGET)

$(TARGET): out/uic/ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile.app: pro/LINEFOLLOWER.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile.app pro/LINEFOLLOWER.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile.app pro/LINEFOLLOWER.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/LINEFOLLOWER1.0.0 || $(MKDIR) obj/LINEFOLLOWER1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/LINEFOLLOWER1.0.0/ && $(COPY_FILE) --parents inc/qcustomplot/qcustomplot.h inc/czujniki.hh inc/data.hh inc/info.hh inc/trasa.hh inc/wykres.hh inc/rs232/odbieranie.hh inc/rs232/transparam.hh inc/mainwindow.h obj/LINEFOLLOWER1.0.0/ && $(COPY_FILE) --parents res/pcb.qrc obj/LINEFOLLOWER1.0.0/ && $(COPY_FILE) --parents src/czujniki.cpp src/data.cpp src/info.cpp src/main.cpp src/mainwindow.cpp src/trasa.cpp src/wykres.cpp src/qcustomplot/qcustomplot.cpp src/rs232/odbieranie.cpp src/rs232/transparam.cpp obj/LINEFOLLOWER1.0.0/ && $(COPY_FILE) --parents ui/mainwindow.ui obj/LINEFOLLOWER1.0.0/ && $(COPY_FILE) --parents langs/diagui_en.ts obj/LINEFOLLOWER1.0.0/ && (cd `dirname obj/LINEFOLLOWER1.0.0` && $(TAR) LINEFOLLOWER1.0.0.tar LINEFOLLOWER1.0.0 && $(COMPRESS) LINEFOLLOWER1.0.0.tar) && $(MOVE) `dirname obj/LINEFOLLOWER1.0.0`/LINEFOLLOWER1.0.0.tar.gz . && $(DEL_FILE) -r obj/LINEFOLLOWER1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile.app


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: out/moc/moc_qcustomplot.cpp out/moc/moc_czujniki.cpp out/moc/moc_info.cpp out/moc/moc_trasa.cpp out/moc/moc_wykres.cpp out/moc/moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) out/moc/moc_qcustomplot.cpp out/moc/moc_czujniki.cpp out/moc/moc_info.cpp out/moc/moc_trasa.cpp out/moc/moc_wykres.cpp out/moc/moc_mainwindow.cpp
out/moc/moc_qcustomplot.cpp: inc/qcustomplot/qcustomplot.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) inc/qcustomplot/qcustomplot.h -o out/moc/moc_qcustomplot.cpp

out/moc/moc_czujniki.cpp: inc/data.hh \
		inc/czujniki.hh
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) inc/czujniki.hh -o out/moc/moc_czujniki.cpp

out/moc/moc_info.cpp: inc/data.hh \
		inc/info.hh
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) inc/info.hh -o out/moc/moc_info.cpp

out/moc/moc_trasa.cpp: inc/data.hh \
		inc/trasa.hh
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) inc/trasa.hh -o out/moc/moc_trasa.cpp

out/moc/moc_wykres.cpp: inc/qcustomplot/qcustomplot.h \
		inc/wykres.hh
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) inc/wykres.hh -o out/moc/moc_wykres.cpp

out/moc/moc_mainwindow.cpp: inc/wykres.hh \
		inc/qcustomplot/qcustomplot.h \
		inc/data.hh \
		inc/czujniki.hh \
		inc/trasa.hh \
		inc/mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) inc/mainwindow.h -o out/moc/moc_mainwindow.cpp

compiler_rcc_make_all: out/rcc/qrc_pcb.cpp
compiler_rcc_clean:
	-$(DEL_FILE) out/rcc/qrc_pcb.cpp
out/rcc/qrc_pcb.cpp: res/pcb.qrc
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name pcb res/pcb.qrc -o out/rcc/qrc_pcb.cpp

compiler_image_collection_make_all: out/uic/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) out/uic/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: out/uic/ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) out/uic/ui_mainwindow.h
out/uic/ui_mainwindow.h: ui/mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic ui/mainwindow.ui -o out/uic/ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

obj/czujniki.o: src/czujniki.cpp inc/czujniki.hh \
		inc/data.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/czujniki.o src/czujniki.cpp

obj/data.o: src/data.cpp inc/data.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/data.o src/data.cpp

obj/info.o: src/info.cpp inc/info.hh \
		inc/data.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/info.o src/info.cpp

obj/main.o: src/main.cpp inc/mainwindow.h \
		inc/wykres.hh \
		inc/qcustomplot/qcustomplot.h \
		inc/data.hh \
		inc/czujniki.hh \
		inc/trasa.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/mainwindow.o: src/mainwindow.cpp inc/mainwindow.h \
		inc/wykres.hh \
		inc/qcustomplot/qcustomplot.h \
		inc/data.hh \
		inc/czujniki.hh \
		inc/trasa.hh \
		out/uic/ui_mainwindow.h \
		inc/info.hh \
		inc/rs232/odbieranie.hh \
		inc/rs232/transparam.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mainwindow.o src/mainwindow.cpp

obj/trasa.o: src/trasa.cpp inc/trasa.hh \
		inc/data.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/trasa.o src/trasa.cpp

obj/wykres.o: src/wykres.cpp inc/wykres.hh \
		inc/qcustomplot/qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/wykres.o src/wykres.cpp

obj/qcustomplot.o: src/qcustomplot/qcustomplot.cpp inc/qcustomplot/qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qcustomplot.o src/qcustomplot/qcustomplot.cpp

obj/odbieranie.o: src/rs232/odbieranie.cpp inc/rs232/transparam.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/odbieranie.o src/rs232/odbieranie.cpp

obj/transparam.o: src/rs232/transparam.cpp inc/rs232/transparam.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/transparam.o src/rs232/transparam.cpp

obj/moc_qcustomplot.o: out/moc/moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_qcustomplot.o out/moc/moc_qcustomplot.cpp

obj/moc_czujniki.o: out/moc/moc_czujniki.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_czujniki.o out/moc/moc_czujniki.cpp

obj/moc_info.o: out/moc/moc_info.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_info.o out/moc/moc_info.cpp

obj/moc_trasa.o: out/moc/moc_trasa.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_trasa.o out/moc/moc_trasa.cpp

obj/moc_wykres.o: out/moc/moc_wykres.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_wykres.o out/moc/moc_wykres.cpp

obj/moc_mainwindow.o: out/moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_mainwindow.o out/moc/moc_mainwindow.cpp

obj/qrc_pcb.o: out/rcc/qrc_pcb.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_pcb.o out/rcc/qrc_pcb.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

